<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Welcome, new traveler!';
 $this->headTitle($title);
 ?>
 <h1><?php 
 if ($hasForm)
 {
   echo $this->escapeHtml($title); 
 }
 ?></h1>
 To create an account, fill these couple fields:
 <br><br>
 <?php
 if ($hasForm)
 {
 $form->setAttribute('action', $this->url('traveler', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('username'));
 echo '<br>';
 echo $this->formRow($form->get('emailAddress'));
 echo '<br>';
 echo $this->formRow($form->get('password'));
 echo '<br><br>';
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 }
