<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'All travelers';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('traveler', array('action'=>'add'));?>">Create a traveler account</a>
 </p>

 <table class="table">
 <tr>
     <th>Pseudo</th>
     <th>Email</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($travelers as $traveler) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($traveler->username);?></td>
     <td><?php echo $this->escapeHtml($traveler->emailAddress);?></td>
     <td>
         <a href="<?php echo $this->url('traveler',
             array('action'=>'edit', 'id' => $traveler->id));?>">Edit</a>
     </td>
     <td>
         <a href="<?php echo $this->url('traveler',
             array('action'=>'delete', 'id' => $traveler->id),
             array('query' => array('origAction' => 'all')));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
