 <?php
 // module/Album/view/album/album/delete.phtml:

 $title = 'Delete your account';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete the account of 
     '<?php echo $this->escapeHtml($traveler->username); ?>' with email
     '<?php echo $this->escapeHtml($traveler->emailAddress); ?>'?
 </p>
 <?php
 $url = $this->url('traveler', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $traveler->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>
