 <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit your account';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
<br>
This is your page. You can update the information about your account using the following fields.
<br><br>
 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'traveler',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('username'));
 echo '<br>';
 echo $this->formRow($form->get('emailAddress'));
 echo '<br><br>';
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
