<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Welcome back, traveler!';
 $this->headTitle($title);
 ?>
 <h1><?php 
 if ($hasForm)
 {
   echo $this->escapeHtml($title); 
 }
 ?></h1>
 
 Please log in to have access to many resources.
 <?php
 if ($hasForm)
 {
 $form->setAttribute('action', $this->url('traveler', array('action' => 'log')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('emailAddress'));
 echo '<br>';
 echo $this->formRow($form->get('password'));
 echo '<br>';
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 }
