#%RAML 1.0
title: Jetlag Articles API
version: v0.1
baseUri: /api/0.1/
mediaType: application/json
types:
  Article:
    type: object
    properties:
      id: integer
      created_at: timestamp
      update_at?: timestamp
      deleted_at?: timestamp
      title: string
      url: string
      description_text: string
      description_media: Picture
      main_place: Place
      is_draft: boolean
      is_public: boolean
      authors: Author_user[]
  Author_user:
    type: object
    properties:
      id: integer
      role: string
  Paragraph:
    type: object
    properties:
      id: integer
      created_at: timestamp
      update_at?: timestamp
      deleted_at?: timestamp
      title?: string
      block_content: Picture | Map | Text | Link
      block_content_type:
        enum: [ picture, map, text, link ]
  Picture:
    type: object
    properties:
      id: integer
      created_at: timestamp
      update_at?: timestamp
      deleted_at?: timestamp
      small_picture?: Link
      medium_picture?: Link
      big_picture?: Link # the fullsize picture as uploaded
      authors: Author_user[]
      taken_at?: timestamp
      main_place?: Place
  Text:
    type: object
    properties:
      id: integer
      created_at: timestamp
      update_at?: timestamp
      deleted_at?: timestamp
      value: string
  Map:
    type: object
    properties:
      id: integer
      created_at: timestamp
      update_at?: timestamp
      deleted_at?: timestamp
      caption?: string
      center: Place
      zoom: integer
      place?: Place # if there is one, we display it as a marker
  Place:
    type: object
    properties:
      id: integer
      label: string # from geocoding service
      latitude: number
      longitude: number
  Link:
    type: object
    properties:
      id: number
      url: string
      mime_type?: string #helpful to know in advance how to handle this link