#%RAML 1.0
title: Jetlag Articles API
version: v0.1
baseUri: /api/0.1/
mediaType:  application/json

types:
  Article : !include article.raml
/articles:
  get:
    description: Get all articles authored (owned or writable) by the logged in user. Limited to 20 results (to be configurable). The content should be enough to display a list of articles (not their full content).
    responses:
      200:
        body:
          application/json:
            type: Article
  post:
    description: Creates a new article as logged in user
    body:
      application/json:
        type: Article
    responses:
      201:
        body:
          application/json:
            properties:
              id: number
              url: string
  /{articleId}:
    get:
      description: Return JSON description of the article
      responses:
        200:
          body:
            application/json:
              type: Article
    put:
      description: Update the entire article and its components
      body:
        application/json:
          type: Article
      responses:
        200:
          body:
            application/json:
              properties:
                id: number
    patch:
      description: Update partially the article and its components
      body:
        application/json:
          type: Article
      responses:
        200:
          body:
            application/json:
              properties:
                id: number
    delete:
      description: Delete (soft) article. The logged in user must be the article's owner.
      responses:
        200:
          body:
            application/json:
              properties:
                id: number
