#%RAML 1.0 
title: Jetlag Articles API
version: v0.1
baseUri: /api/0.1/
mediaType:  application/json
types:
resourceTypes:
traits:
/articles:
  get:
    description: Get all articles authored (owned or writable) by the logged in user. Limited to 20 results (to be configurable). The content should be enough to display a list of articles (not their full content).
    responses:
      200:
        body:
          application/json:
            schema: article
  post:
    description: Creates a new article as logged in user
    body:
      application/json
        schema: article
    responses:
      201:
        body:
          application/json:
            id: number
            url: string
  /{articleId}:
    get:
      description: Return JSON description of the article
      responses:
        200:
          body:
            application/json:
              schema: article
    put:
      description: Update the article and its components
      body:
        application/json
          schema: article
      responses:
        200:
          body:
            application/json:
              id: number
    delete:
      description: Delete (soft) article. The logged in user must be the article's owner.
      responses:
        200:
          body:
            application/json:
              id: number

