#%RAML 1.0
title: schemas for article and its children
schemas:
 - Article: |
    {
      "type": "object",
      "properties": {
        "id": {
          "type": "number",
          "required": false,
        },
        "title": {
          "type": "string",
          "required": true,
          "minLength": 3,
          "maxLength": 200
        },
        "url": {
          "description" : "the url to access the article's web page. Only used when reading from the server.",
          "type": "string",
          "required": false,
          "minLength": 3,
          "maxLength": 200
        },
        "descriptionText": {
          "type": "string",
          "required": false,
          "minLength": 3,
          "maxLength": 500
        },
        "descriptionMedia": {
          "type": "object",
          "required": false,
          "schema" : Picture
        },
        "isDraft": {
          "type": "boolean",
          "required": false
        },
        "isPublic": {
          "type": "boolean",
          "required": false
        },
        "authorUsers": {
          "type": "AuthorUser[]",
          "required": false,
          "schema" : AuthorUser
        },
        "authorUsers": {
          "type": "Paragraph[]",
          "required": false,
          "schema" : Paragraph
        }
      }
    }
 - Picture: |
    {
      "type": "object",
      "properties": {
        "id": {
          "type": "number",
          "required": false
        },
        "title": {
          "type": "string",
          "required": false,
          "minLength": 3,
          "maxLength": 200
        },
        "url": {
          "type": "string",
          "required": false,
          "minLength": 3,
          "maxLength": 100
        },
        "small_url": {
          "type": "string",
          "required": false,
          "minLength": 3,
          "maxLength": 100
        },
        "medium_url": {
          "type": "string",
          "required": false,
          "minLength": 3,
          "maxLength": 100
        },
        "big_url": {
          "type": "string",
          "required": false,
          "minLength": 3,
          "maxLength": 100
        }
      }
    }
 - AuthorUser: |
    {
      "type": "object",
      "properties": {
        "id": {
          "type": "number",
          "required": false
        },
        "role": {
          "type": "string",
          "required": false,
          "minLength": 5,
          "maxLength": 10
        }
      }
    }
 - Paragraph: |
    {
      "type": "object",
      "properties": {
        "id": {
          "type": "number",
          "required": false
        },
        "title": {
          "type": "string",
          "required": true,
          "minLength": 3,
          "maxLength": 200
        },
        "blockContent": {
          "type": "Picture",
          "required": false,
          "schema" : Picture
        },
        "place": {
          "type": "Place",
          "required": false,
          "schema" : Place
        },
        "date": {
          "type": "string",
          "required": false
        },
        "weather": {
          "type": "string",
          "required": false
        },
        "isDraft": {
          "type": "boolean",
          "required": false
        }
      }
    }
 - Place: |
    {
      "type": "object",
      "properties": {
        "id": {
          "type": "number",
          "required": false
        },
        "latitude": {
          "type": "double",
          "required": true
        },
        "longitude": {
          "type": "double",
          "required": true
        },
        "altitude": {
          "type": "double",
          "required": false
        },
        "description": {
          "type": "string",
          "required": false
        }
      }
    }
